-- Rename EMPLOYEE to MAKER and BRANCH_MANAGER to CHECKER.
UPDATE users SET role = 'MAKER' WHERE role IN ('EMPLOYEE', 'USER');
UPDATE users SET role = 'CHECKER' WHERE role = 'BRANCH_MANAGER';

ALTER TABLE users
  ALTER COLUMN role SET DEFAULT 'MAKER';
